export const SIGNUP_NEXT_STEP = 'SIGNUP_NEXT_STEP'
export const SIGNUP_PREV_STEP = 'SIGNUP_PREV_STEP'

export const SIGNUP_STEP1_SAVING = 'SIGNUP_STEP1_SAVING'
export const SIGNUP_STEP1_SAVED = 'SIGNUP_STEP1_SAVED'

export const SIGNUP_STEP2_SAVING = 'SIGNUP_STEP2_SAVING'
export const SIGNUP_STEP2_SAVED = 'SIGNUP_STEP2_SAVED'

export const SIGNUP_STEP3_SAVING = 'SIGNUP_STEP3_SAVING'
export const SIGNUP_STEP3_SAVED = 'SIGNUP_STEP3_SAVED'

export const CHECKOUT_START = 'CHECKOUT_START'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL'

export const CHANGE_PHONE_SUCCESS = 'CHANGE_PHONE_SUCCESS'

export const SIGNUP_CONFIRMATION_SAVING = 'SIGNUP_CONFIRMATION_SAVING'
export const SIGNUP_CONFIRMATION_SAVED = 'SIGNUP_CONFIRMATION_SAVED'

export const AUTH_LOAD_START = 'AUTH_LOAD_START'
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL'

export const APPOINTMENTS_LOAD_START = 'APPOINTMENTS_LOAD_START'
export const APPOINTMENTS_LOAD_SUCCESS = 'APPOINTMENTS_LOAD_SUCCESS'
export const APPOINTMENTS_SELECT = 'APPOINTMENTS_SELECT'

export const APPOINTMENTS_LOCATIONS_LOAD_SUCCESS = 'APPOINTMENTS_LOCATIONS_LOAD_SUCCESS'
export const APPOINTMENTS_LOCATIONS_SELECT = 'APPOINTMENTS_LOCATIONS_SELECT'

export const SIGNUP_FETCH_SUCCESS = 'SIGNUP_FETCH_SUCCESS'
export const SIGNUP_PROGRESS_UPDATED = 'SIGNUP_PROGRESS_UPDATED'

export const GEOLOCATION_GET_POSITION_SUCCESS = 'GEOLOCATION_GET_POSITION_SUCCESS'
export const GEOLOCATION_GET_POSITION_START = 'GEOLOCATION_GET_POSITION_START'
export const GEOLOCATION_GET_POSITION_FAIL = 'GEOLOCATION_GET_POSITION_FAIL'

export const GEOLOCATION_GET_GEOCODE_START = 'GEOLOCATION_GET_POSITION_START'
export const GEOLOCATION_GET_GEOCODE_COMPLETE = 'GEOLOCATION_GET_GEOCODE_COMPLETE'
export const GEOLOCATION_GET_GEOCODE_FAIL = 'GEOLOCATION_GET_GEOCODE_FAIL'

export const PHONE_VERIFICATION_START = 'PHONE_VERIFICATION_START'
export const PHONE_VERIFICATION_COMPLETE = 'PHONE_VERIFICATION_COMPLETE'
export const PHONE_VERIFICATION_FAIL = 'PHONE_VERIFICATION_FAIL'
export const PHONE_RESEND_VERIFICATION_COMPLETE = 'PHONE_RESEND_VERIFICATION_COMPLETE'

export const WINDOW_RESIZE = 'WINDOW_RESIZE'

export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'

export const UPDATE_PERCENTAGE_PROGRESS = 'UPDATE_PERCENTAGE_PROGRESS'
export const SIGNUP_SELECT_STEP = 'SIGNUP_SELECT_STEP'